[package]
name = "rust_practice"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

[workspace]
members = ["concept", "datastructure", "hash_map", "single_linked_list"]

[dependencies]
single_linked_list = { path = "single_linked_list" }
concept = { path = "concept" }
datastructure = { path = "datastructure" }
hash_map = { path = "hash_map" }
